# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:
  custom.event.home_page_event:
      class: AppBundle\ExceptionEventSubscriber
      tags:
          - { name: kernel.event_listener, event: kernel.exception }